### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`

### ISSUE THREAD

**Issue by gwen233666** [city-super/Scaffold-GS#83]
Traceback (most recent call last):
  File "train.py", line 527, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), dataset,  args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, wandb, logger)
  File "train.py", line 87, in training
    scene = Scene(dataset, gaussians, ply_path=ply_path, shuffle=False)
  File "/home/huigang/Scaffold-GS/scene/__init__.py", line 82, in __init__
    self.train_cameras[resolution_scale] = cameraList_from_camInfos(scene_info.train_cameras, resolution_scale, args)
  File "/home/huigang/Scaffold-GS/utils/camera_utils.py", line 59, in cameraList_from_camInfos
    camera_list.append(loadCam(args, id, c, resolution_scale))
  File "/home/huigang/Scaffold-GS/utils/camera_utils.py", line 53, in loadCam
    image_name=cam_info.image_name, uid=id, data_device=args.data_device)
  File "/home/huigang/Scaffold-GS/scene/cameras.py", line 56, in __init__
    self.full_proj_transform = (self.world_view_transform.unsqueeze(0).bmm(self.projection_matrix.unsqueeze(0))).squeeze(0)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemmStridedBatched( handle, opa, opb, m, n, k, &alpha, a, lda, stridea, b, ldb, strideb, &beta, c, ldc, stridec, num_batches)`

Hello, thank you for your excellent work, but I have encountered the following problems during training. Could you please give me some advice? Thank you in advance.

**Comment by inspirelt** [comment]
Hi, I would suggest you to try to change the pytorch and cuda version.

**Comment by Xun2001** [comment]
Hello, I also encountered the same problem. My CUDA version is 11.6, and Torch is also the corresponding version of 11.6. Have you solved this problem?

**Comment by Xun2001** [comment]
Here is my CUDA and Torch version
```
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver  
Copyright (c) 2005-2021 NVIDIA Corporation  
Built on Fri_Dec_17_18:16:03_PST_2021  
Cuda compilation tools, release 11.6, V11.6.55  
Build cuda_11.6.r11.6/compiler.30794723_0
```

```
>>>  import torch  
>>> print(torch.version.cuda)  
11.6
>>> print(torch.__version__)
1.12.1
```

**Comment by Xun2001** [comment]
I have solved this problem by `unset LD_LIBRARY_PATH`
